# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cnella <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/30 21:00:27 by cnella            #+#    #+#              #
#    Updated: 2018/10/30 21:05:34 by cnella           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = ./srcs/ft_putchar.c ./srcs/ft_putnbr.c ./srcs/ft_strncmp.c ./srcs/ft_atoi.c ./srcs/main.c

all:
	gcc $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

re: clean all
