# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cnella <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/01 17:34:11 by cnella            #+#    #+#              #
#    Updated: 2018/11/01 18:02:30 by cnella           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = ./*.c

all:
	gcc -o $(NAME) $(SRC) -Wall -Wextra -Werror
clean:
	rm -f *.o
fclean:
	rm -f $(NAME)
re: fclean re
